import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header'

const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <Header />
        <main
          className='min-h-screen flex-1 
                    overflow-y-auto overflow-hidden 
                    py-24 px-8 bg-secondary/20 
                    flex flex-col'
        >
          {children}
        </main>
      </body>
    </html>
  )
}
